In [2]:
import numpy as np
A = np.array([[56.0, 0.0, 4.4, 68.0],
            [1.2, 104.0, 52.0, 8.0],
            [1.8, 135.0, 99.0, 0.9]])

In [3]:
print(A)

[[ 56.    0.    4.4  68. ]
 [  1.2 104.   52.    8. ]
 [  1.8 135.   99.    0.9]]


In [19]:
cal = A.sum(axis=0)

In [20]:
cal

array([ 59. , 239. , 155.4,  76.9])

In [21]:
percentage = A/cal*100

In [22]:
percentage

array([[94.91525424,  0.        ,  2.83140283, 88.42652796],
       [ 2.03389831, 43.51464435, 33.46203346, 10.40312094],
       [ 3.05084746, 56.48535565, 63.70656371,  1.17035111]])

In [3]:
a = np.random.randn(2, 3) # a.shape = (2, 3)
b = np.random.randn(2, 1) # b.shape = (2, 1)
c = a + b

In [4]:
c

array([[ 1.01396159,  0.57027948,  1.33478101],
       [ 1.58646499, -0.12656823, -0.3715994 ]])

In [5]:
c = a*b

In [6]:
c

array([[ 0.18819843,  0.07966315,  0.26667855],
       [ 0.53042663, -0.28998247, -0.40733326]])

In [12]:
a = np.random.randn(4, 3) # a.shape = (4, 3)
b = np.random.randn(1, 3) # b.shape = (3, 2)
c = a*b

In [13]:
a = np.random.randn(3, 3)
b = np.random.randn(3, 1)
c = a*b

In [14]:
c.shape

(3, 3)