In [1]:
import numpy as np

a = np.random.rand(5)

In [2]:
print(a)

[0.19000345 0.04302524 0.69945864 0.62299581 0.69933364]


In [3]:
print(a.shape)

(5,)


In [6]:
print(a.T)

[0.19000345 0.04302524 0.69945864 0.62299581 0.69933364]


In [7]:
print(np.dot(a, a.T))

1.4043861853817778


In [8]:
a = np.random.randn(5, 1)

In [9]:
a

array([[-0.80394923],
       [-2.54448905],
       [ 0.96900719],
       [-1.16754394],
       [ 0.04086218]])

In [11]:
a.T

array([[-0.80394923],
       [-2.54448905],
       [ 0.96900719],
       [-1.16754394],
       [ 0.04086218]])

In [12]:
print(np.dot(a, a.T))

[[ 6.46334368e-01  2.04564002e+00 -7.79032586e-01  9.38646057e-01
  -3.28511208e-02]
 [ 2.04564002e+00  6.47442452e+00 -2.46562818e+00  2.97080278e+00
  -1.03973378e-01]
 [-7.79032586e-01 -2.46562818e+00  9.38974933e-01 -1.13135848e+00
   3.95957493e-02]
 [ 9.38646057e-01  2.97080278e+00 -1.13135848e+00  1.36315886e+00
  -4.77083945e-02]
 [-3.28511208e-02 -1.03973378e-01  3.95957493e-02 -4.77083945e-02
   1.66971802e-03]]


In [13]:
assert(a.shape==(5, 1))

In [16]:
assert(a.shape==(5, 1))

In [17]:
a = np.random.randn(5)

In [18]:
assert(a.shape==(5, 1))

AssertionError: 